using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using OutSystems.HubEdition.RuntimePlatform;

using Amazon.Athena.Model;
using Newtonsoft.Json;
using OutSystems.NssAmazonAthenaConnector;

namespace OutSystems.NssGRAX_AthenaConnector
{
    public class CssGRAX_AthenaConnector : IssGRAX_AthenaConnector
    {
		/// <summary>
		/// Initiates the AmazonAthenaClient
		/// </summary>
		/// <param name="ssAuthenticationInfo"></param>
		public void MssAthena_Login(RCAthena_AuthenticationInfoRecord ssAuthenticationInfo) {
            AmazonAthena.Instance.Login(ssAuthenticationInfo.ssSTAthena_AuthenticationInfo.ssAwsAccessKeyId, ssAuthenticationInfo.ssSTAthena_AuthenticationInfo.ssAwsSecretAccessKey, ssAuthenticationInfo.ssSTAthena_AuthenticationInfo.ssAwsRegion);
        } // MssAthena_Login


		/// <summary>
		/// Provides a list of available query IDs only for queries saved in the specified workgroup. Requires that you have access to the specified workgroup. If a workgroup is not specified, lists the saved queries for the primary workgroup.
		/// </summary>
		/// <param name="ssWorkGroup">The name of the workgroup from which the named queries are being returned. If a workgroup is not specified, the saved queries for the primary workgroup are returned. </param>
		/// <param name="ssIn_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssMaxResults">The maximum number of queries to return in this request. </param>
		/// <param name="ssQueryIds">The list of unique query IDs. </param>
		/// <param name="ssOut_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		public void MssAthena_ListNamedQueries(string ssWorkGroup, string ssIn_NextToken, int ssMaxResults, out RLTextRecordList ssQueryIds, out string ssOut_NextToken)
		{
			ssQueryIds = new RLTextRecordList();

			List<string> queryIds = AmazonAthena.Instance.ListNamedQueries(ssWorkGroup, ssIn_NextToken, ssMaxResults, out ssOut_NextToken);

			foreach (string queryId in queryIds)
			{
				ssQueryIds.Add(new RCTextRecord()
				{
					ssSTText = new STTextStructure()
					{
						ssValue = queryId
					}
				});
			}

		} // MssAthena_ListNamedQueries


		/// <summary>
		/// Returns information about a single query. Requires that you have access to the workgroup in which the query was saved. 
		/// </summary>
		/// <param name="ssNamedQueryId"></param>
		/// <param name="ssNamedQuery"></param>
		public void MssAthena_GetNamedQuery(string ssNamedQueryId, out RCAthena_NamedQueryRecord ssNamedQuery) {
			ssNamedQuery = new RCAthena_NamedQueryRecord(null);

            NamedQuery namedQuery = AmazonAthena.Instance.GetNamedQuery(ssNamedQueryId);

            ssNamedQuery.ssSTAthena_NamedQuery = new STAthena_NamedQueryStructure()
            {
                ssDatabase = namedQuery.Database,
                ssDescription = namedQuery.Description,
                ssName = namedQuery.Name,
                ssNamedQueryId = namedQuery.NamedQueryId,
                ssQueryString = namedQuery.QueryString,
                ssWorkGroup = namedQuery.WorkGroup
            };

        } // MssAthena_GetNamedQuery

		/// <summary>
		/// Runs the SQL query statements contained in the Query. Requires you to have access to the workgroup in which the query ran. Running queries against an external catalog requires GetDataCatalog permission to the catalog
		/// </summary>
		/// <param name="ssClientRequestToken">A unique case-sensitive string used to ensure the request to create the query is idempotent (executes only once). If another StartQueryExecution request is received, the same response is returned and another query is not created. If a parameter has changed, for example, the QueryString, an error is returned. </param>
		/// <param name="ssQueryExecutionContext">The database within which the query executes.</param>
		/// <param name="ssQueryString">The SQL query statements to be executed. </param>
		/// <param name="ssWorkGroup">The name of the workgroup in which the query is being started. </param>
		/// <param name="ssResultConfiguration">Specifies information about where and how to save the results of the query execution. If the query runs in a workgroup, then workgroup&apos;s settings may override query settings. This affects the query results location. The workgroup settings override is specified in EnforceWorkGroupConfiguration (true/false) in the WorkGroupConfiguration</param>
		/// <param name="ssQueryExecutionId">The unique ID of the query that ran as a result of this request. </param>
		public void MssAthena_StartQueryExecution(string ssClientRequestToken, string ssQueryString, string ssWorkGroup, RCAthena_QueryExecutionContextRecord ssQueryExecutionContext, RCAthena_ResultConfigurationRecord ssResultConfiguration, out string ssQueryExecutionId) {
			QueryExecutionContext queryExecutionContext = null;
			ResultConfiguration resultConfiguration = null;

			if (!string.IsNullOrEmpty(ssQueryExecutionContext.ssSTAthena_QueryExecutionContext.ssCatalog) ||
				!string.IsNullOrEmpty(ssQueryExecutionContext.ssSTAthena_QueryExecutionContext.ssDatabase))
			{
				queryExecutionContext = new QueryExecutionContext()
				{
					Catalog = ssQueryExecutionContext.ssSTAthena_QueryExecutionContext.ssCatalog,
					Database = ssQueryExecutionContext.ssSTAthena_QueryExecutionContext.ssDatabase
				};
			}

			if (!string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssOutputLocation) ||
				!string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssEncryptionOption) ||
				!string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssKmsKey))
			{
				resultConfiguration = new ResultConfiguration()
				{
					OutputLocation = ssResultConfiguration.ssSTAthena_ResultConfiguration.ssOutputLocation
				};

				if (!string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssEncryptionOption) ||
					!string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssKmsKey))
				{

					resultConfiguration.EncryptionConfiguration = new EncryptionConfiguration()
					{
						EncryptionOption = string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssEncryptionOption) ? null : ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssEncryptionOption,
						KmsKey = string.IsNullOrEmpty(ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssKmsKey) ? null : ssResultConfiguration.ssSTAthena_ResultConfiguration.ssEncryptionConfiguration.ssSTAthena_EncryptionConfiguration.ssKmsKey
					};
				}
			}

			ssQueryExecutionId = AmazonAthena.Instance.StartQueryExecution(ssClientRequestToken, ssQueryString, ssWorkGroup, queryExecutionContext, resultConfiguration);


		} // MssAthena_StartQueryExecution

		/// <summary>
		/// Streams the results of a single query execution specified by QueryExecutionId from the Athena query results location in Amazon S3
		/// </summary>
		/// <param name="ssQueryExecutionId">The unique ID of the query execution. </param>
		/// <param name="ssIn_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssMaxResults">The maximum number of results (rows) to return in this request. (default = 100)</param>
		/// <param name="ssRows">The rows in the table. (in JSON Format)</param>
		/// <param name="ssOut_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssUpdateCount">The number of rows inserted with a CREATE TABLE AS SELECT statement. </param>
		public void MssAthena_GetQueryResults(string ssQueryExecutionId, string ssIn_NextToken, int ssMaxResults, out string ssRows, out string ssOut_NextToken, out int ssUpdateCount) {

			List<Row> rows = AmazonAthena.Instance.GetQueryResults(ssQueryExecutionId, ssIn_NextToken, ssMaxResults, out ssOut_NextToken, out ssUpdateCount);

			ssRows = JsonConvert.SerializeObject(rows);
			
		} // MssAthena_GetQueryResults

		/// <summary>
		/// Returns information about a single execution of a query if you have access to the workgroup in which the query ran. Each time a query executes, information about the query execution is saved with a unique ID.
		/// </summary>
		/// <param name="ssQueryExecutionId">The unique ID of the query execution.</param>
		/// <param name="ssQueryExecution"></param>
		public void MssAthena_GetQueryExecution(string ssQueryExecutionId, out RCAthena_QueryExecutionRecord ssQueryExecution)
		{
			QueryExecution queryExecution = AmazonAthena.Instance.GetQueryExecution(ssQueryExecutionId);

			ssQueryExecution = new RCAthena_QueryExecutionRecord()
			{
				ssSTAthena_QueryExecution = new STAthena_QueryExecutionStructure()
				{
					ssQueryExecutionId = queryExecution.QueryExecutionId,
					ssQuery = queryExecution.Query,
					ssStatementType = queryExecution.StatementType.Value,
					ssWorkGroup = queryExecution.WorkGroup,
					ssEngineVersion = new RCAthena_EngineVersionRecord()
					{
						ssSTAthena_EngineVersion = new STAthena_EngineVersionStructure()
						{
							ssSelectedEngineVersion = queryExecution.EngineVersion.SelectedEngineVersion,
							ssEffectiveEngineVersion = queryExecution.EngineVersion.EffectiveEngineVersion
						}
					},
					ssQueryExecutionContext = new RCAthena_QueryExecutionContextRecord()
					{
						ssSTAthena_QueryExecutionContext = new STAthena_QueryExecutionContextStructure()
						{
							ssDatabase = queryExecution.QueryExecutionContext.Database,
							ssCatalog = queryExecution.QueryExecutionContext.Catalog
						}
					},
					ssResultConfiguration = new RCAthena_ResultConfigurationRecord()
					{
						ssSTAthena_ResultConfiguration = new STAthena_ResultConfigurationStructure()
						{
							ssOutputLocation = queryExecution.ResultConfiguration.OutputLocation,
							ssEncryptionConfiguration =
							new RCAthena_EncryptionConfigurationRecord()
							{
								ssSTAthena_EncryptionConfiguration = new STAthena_EncryptionConfigurationStructure()
								{
									ssEncryptionOption = queryExecution.ResultConfiguration.EncryptionConfiguration != null ? queryExecution.ResultConfiguration.EncryptionConfiguration.EncryptionOption.Value : "",
									ssKmsKey = queryExecution.ResultConfiguration.EncryptionConfiguration != null ? queryExecution.ResultConfiguration.EncryptionConfiguration.KmsKey : "",
								}
							}
						}
					},
					ssStatus = new RCAthena_QueryExecutionStatusRecord()
					{
						ssSTAthena_QueryExecutionStatus = new STAthena_QueryExecutionStatusStructure()
						{
							ssCompletionDateTime = queryExecution.Status.CompletionDateTime,
							ssState = queryExecution.Status.State.Value,
							ssStateChangeReason = queryExecution.Status.StateChangeReason,
							ssSubmissionDateTime = queryExecution.Status.SubmissionDateTime
						}
					},
					ssStatistics = new RCAthena_QueryExecutionStatisticsRecord()
					{
						ssSTAthena_QueryExecutionStatistics = new STAthena_QueryExecutionStatisticsStructure()
						{
							ssDataManifestLocation = queryExecution.Statistics.DataManifestLocation,
							ssDataScannedInBytes = queryExecution.Statistics.DataScannedInBytes,
							ssEngineExecutionTimeInMillis = queryExecution.Statistics.EngineExecutionTimeInMillis,
							ssQueryPlanningTimeInMillis = queryExecution.Statistics.QueryPlanningTimeInMillis,
							ssQueryQueueTimeInMillis = queryExecution.Statistics.QueryQueueTimeInMillis,
							ssServiceProcessingTimeInMillis = queryExecution.Statistics.ServiceProcessingTimeInMillis,
							ssTotalExecutionTimeInMillis = queryExecution.Statistics.TotalExecutionTimeInMillis
						}
					}
				}
			};

		} // MssAthena_GetQueryExecution

	} // CssExtension
} // OutSystems.NssExtension