using System;
using System.Collections;
using System.Data;
using OutSystems.HubEdition.RuntimePlatform;

namespace OutSystems.NssGRAX_AthenaConnector {

	public interface IssGRAX_AthenaConnector {

		/// <summary>
		/// Initiates the AmazonAthenaClient
		/// </summary>
		/// <param name="ssAuthenticationInfo"></param>
		void MssAthena_Login(RCAthena_AuthenticationInfoRecord ssAuthenticationInfo);

		/// <summary>
		/// Returns information about a single query. Requires that you have access to the workgroup in which the query was saved.
		/// </summary>
		/// <param name="ssNamedQueryId">The unique ID of the query. Use ListNamedQueries to get query IDs. </param>
		/// <param name="ssNamedQuery">Named Query Object</param>
		void MssAthena_GetNamedQuery(string ssNamedQueryId, out RCAthena_NamedQueryRecord ssNamedQuery);

		/// <summary>
		/// Runs the SQL query statements contained in the Query. Requires you to have access to the workgroup in which the query ran. Running queries against an external catalog requires GetDataCatalog permission to the catalog
		/// </summary>
		/// <param name="ssClientRequestToken">A unique case-sensitive string used to ensure the request to create the query is idempotent (executes only once). If another StartQueryExecution request is received, the same response is returned and another query is not created. If a parameter has changed, for example, the QueryString, an error is returned. </param>
		/// <param name="ssQueryString">The SQL query statements to be executed. </param>
		/// <param name="ssWorkGroup">The name of the workgroup in which the query is being started. </param>
		/// <param name="ssQueryExecutionContext">The database within which the query executes.</param>
		/// <param name="ssResultConfiguration">Specifies information about where and how to save the results of the query execution. If the query runs in a workgroup, then workgroup&apos;s settings may override query settings. This affects the query results location. The workgroup settings override is specified in EnforceWorkGroupConfiguration (true/false) in the WorkGroupConfiguration</param>
		/// <param name="ssQueryExecutionId">The unique ID of the query that ran as a result of this request. </param>
		void MssAthena_StartQueryExecution(string ssClientRequestToken, string ssQueryString, string ssWorkGroup, RCAthena_QueryExecutionContextRecord ssQueryExecutionContext, RCAthena_ResultConfigurationRecord ssResultConfiguration, out string ssQueryExecutionId);

		/// <summary>
		/// Streams the results of a single query execution specified by QueryExecutionId from the Athena query results location in Amazon S3
		/// </summary>
		/// <param name="ssQueryExecutionId">The unique ID of the query execution. </param>
		/// <param name="ssIn_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssMaxResults">The maximum number of results (rows) to return in this request. (default = 50)</param>
		/// <param name="ssRows">The rows in the table. (in JSON Format)</param>
		/// <param name="ssOut_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssUpdateCount">The number of rows inserted with a CREATE TABLE AS SELECT statement. </param>
		void MssAthena_GetQueryResults(string ssQueryExecutionId, string ssIn_NextToken, int ssMaxResults, out string ssRows, out string ssOut_NextToken, out int ssUpdateCount);

		/// <summary>
		/// Provides a list of available query IDs only for queries saved in the specified workgroup. Requires that you have access to the specified workgroup. If a workgroup is not specified, lists the saved queries for the primary workgroup.
		/// </summary>
		/// <param name="ssWorkGroup">The name of the workgroup from which the named queries are being returned. If a workgroup is not specified, the saved queries for the primary workgroup are returned. </param>
		/// <param name="ssIn_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		/// <param name="ssMaxResults">The maximum number of results (rows) to return in this request. (default = 50)</param>
		/// <param name="ssQueryIds">The list of unique query IDs. </param>
		/// <param name="ssOut_NextToken">A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call. </param>
		void MssAthena_ListNamedQueries(string ssWorkGroup, string ssIn_NextToken, int ssMaxResults, out RLTextRecordList ssQueryIds, out string ssOut_NextToken);

		/// <summary>
		/// Returns information about a single execution of a query if you have access to the workgroup in which the query ran. Each time a query executes, information about the query execution is saved with a unique ID.
		/// </summary>
		/// <param name="ssQueryExecutionId">The unique ID of the query execution.</param>
		/// <param name="ssQueryExecution">Query Execution Object</param>
		void MssAthena_GetQueryExecution(string ssQueryExecutionId, out RCAthena_QueryExecutionRecord ssQueryExecution);

	} // IssGRAX_AthenaConnector

} // OutSystems.NssGRAX_AthenaConnector
